config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cars#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars do
    resources :bookings
  end
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user = current_user
    @booking.total_price = @car.price * (@booking.end_date - @booking.start_date).to_i
    if @booking.save!
      redirect_to car_booking_path(@car, @booking)
    else
      render 'cars/show'
    end
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.save
    redirect_to root_path
  end

  def show
    @car = Car.find(params[:car_id])
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to root_path, notice: 'Booking successfully destroyed.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end

  private

  def car_params
    params.require(:car).permit(:brand, :model, :photo, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container global">
  <div class="display">
    <h1>Vos réservations</h1>
  </div>

  <div>
    <ol>
      <% @bookings.each do |booking| %>
      <li><%= booking.car.brand %> <%= booking.car.model %> du <%= booking.start_date %> au <%= booking.end_date %>
      <%= link_to "Annuler", booking_path(booking), method: :delete, data: { confirm: "Are you sure?" }, class: 'backlink' %></li>
      <% end %>
    </ol>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Détails de votre réservation</h1>


<br>
<br>
<div class="container booking">
  <div class="container">
    <h1> Réservation de votre <%= @car.brand %> <%= @car.model %></h1>
  </div>
  <div class="container">
    <p>Du <%= @booking.start_date %></p>
    <p>Au <%= @booking.end_date %></p>
    <h1>Pour un prix de <%= @booking.total_price %> €</h1>
    <%= link_to "Continuer", car_bookings_path(@car), class: 'backlink' %>
  </div>
</div>

<%# This is a great comment! %>

app/views/cars/index.html.erb
<div>
  <h1>Vivez un moment inoubliable !</h1>
</div>

<div class="lists-car">
  <ul>
    <% @cars.each do |car| %>
      <h1><%= car.brand %></h1>
      <h2><%= car.model %></h2>
      <h3><%= car.price %> €</h3>
      <%= image_tag car.car_image, width: 400%>
      <p><%= link_to "Réserver", car_path(car), class:"button-validation" %></p>
      <br>
      <br>
    <% end %>
  </ul>
</div>

app/views/cars/show.html.erb
<p>Hello !</p>

<h1><%= @car.brand %></h1>
<h2><%= @car.model %></h2>
<h2><%= @car.price %>€</h2>
<%= image_tag @car.car_image, width: 400%>


<h2>Réservation</h2>
<%= simple_form_for [@car, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    Suivez-nous :
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="slogan">
    I love code <i class="fa-solid fa-laptop-code"></i> with Le Wagon Marseille !
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav">
  <div class="nav-header">
    <div class="nav-title">
      <%= image_tag "https://api.iconify.design/logos/assembla-icon.svg"%>
      Mon app
    </div>
  </div>

  <div class="nav-links">
      <%= link_to "Accueil", root_path, class: "nav-link" %>
      <a href="//github.io/jo_geek" target="_blank">Github</a>
    <% if user_signed_in? %>
        <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <%= image_tag "https://api.iconify.design/emojione-monotone/person-bowing.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
        <%= link_to "Me connecter", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>